name: Release Build

on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            archive: zip
            artifact: 1.1.0-windows.zip

          - os: ubuntu-latest
            archive: tar.gz
            artifact: 1.1.0-linux.tar.gz

          - os: macos-latest
            archive: tar.gz
            artifact: 1.1.0-macos.tar.gz

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSYS2
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          install: make mingw-w64-x86_64-gcc

      - name: Build
        run: make

      - name: Prepare package
        shell: bash
        run: |
          cp LICENSE package/
          cp README.md package/

          if [ "$RUNNER_OS" = "Windows" ]; then
            cp bin/zabimg.exe package/
          else
            cp bin/zabimg package/
          fi

      - name: Create ZIP archive
        if: matrix.archive == 'zip'
        shell: bash
        run: |
          cd package
          7z a ../${{ matrix.artifact }} *

      - name: Create TAR.GZ archive
        if: matrix.archive == 'tar.gz'
        shell: bash
        run: |
          tar -czf ${{ matrix.artifact }} -C package .

      - name: Upload Release Archive
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ matrix.artifact }}
